[package]
name = "clovers-shader"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", rev = "7e83721978ccfb9132e6de262c6e1789811cfb4d", features = ["glam"] }
