[package]
name = "clovers-shader"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", rev = "71d6001bede77f26d41835bd04e4a53f2f1a2788", features = ["glam"] }
