[package]
name = "clovers"
version = "0.1.0"
authors = ["Walther <veeti.haapsamo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.5"
nalgebra = "0.21.1"
rayon = "1.3.1"
rand = "0.7.3"
chrono = "0.4.11"
humantime = "2.0.1"
indicatif = { version = "0.15.0", features = ["rayon"] }
clap = "3.0.0-beta.1"
pixels = "0.0.4"
winit = "0.22.2"
winit_input_helper = "0.7.0"
