[workspace]
resolver = "2"

members = ["clovers", "clovers-cli"]

[profile.release]
# TODO: temporarily disabled due to slow build times during dev
# codegen-units = 1
# lto = "fat"

[profile.profiling]
inherits = "release"
debug = true
