[package]
name = "clovers-app"
version = "0.1.0"
authors = ["Walther <veeti.haapsamo@gmail.com>"]
edition = "2018"


[dependencies]
# clovers itself
clovers = { path = "../clovers" }
# Required for everything
nalgebra = { version = "0.23.1", features = ["serde-serialize"] }
rayon = "1.5.0"
rand = "0.7.3"
serde = { version = "1.0.118", features = ["derive", "rc"] }
serde_json = "1.0.60"
# Required for CLI
image = { version = "0.23.12"}
chrono = { version = "0.4.19"}
humantime = { version = "2.0.1"}
indicatif = { version = "0.15.0", features = ["rayon"] }
clap = { version = "3.0.0-beta.2" }
toml = { version = "0.5.7" }
# Required for GUI
pixels = { version = "0.5.0" }
winit = { version = "0.24.0" }
winit_input_helper = { version = "0.9.0" }

[dev-dependencies]
