[package]
name = "clovers-app"
version = "0.1.0"
authors = ["Walther <veeti.haapsamo@gmail.com>"]
edition = "2018"
publish = false


[dependencies]
# clovers itself
clovers = { path = "../clovers" }
# Required for everything
rayon = "1.5.0"
rand = "0.8.4"
serde = { version = "1.0.118", features = ["derive", "rc"] }
serde_json = "1.0.60"
indicatif = { version = "0.16.0", features = ["rayon"] }
clap = { version = "3.0.0-beta.2" }
# Required for GUI
pixels = { version = "0.5.0" }
winit = { version = "0.24.0" }
winit_input_helper = { version = "0.9.0" }

[dev-dependencies]
