[package]
name = "clovers-cli"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "clovers-cli"
path = "src/main.rs"

[lib]
# For testing purposes
name = "clovers_draw_cpu"
path = "src/draw_cpu.rs"

[dependencies]
# Internal
clovers = { path = "../clovers", features = [
  "serde-derive",
  "stl",
  "traces",
  "gl_tf",
], default-features = false }

# External
clap = { version = "4.5.1", features = ["std", "derive"] }
human_format = "1.1.0"
humantime = "2.1.0"
image = { version = "0.24.9", features = ["png"], default-features = false }
img-parts = "0.3.0"
indicatif = { version = "0.17.8", features = [
  "rayon",
], default-features = false }
palette = { version = "0.7.5", features = ["serializing"] }
rand = { version = "0.8.5", features = ["small_rng"], default-features = false }
rayon = "1.9.0"
serde = { version = "1.0.197", features = ["derive"], default-features = false }
serde_json = { version = "1.0", features = ["alloc"], default-features = false }
time = { version = "0.3.34", default-features = false }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["time"] }

[dev-dependencies]
divan = "0.1.14"
proptest = "1"

[[bench]]
name = "draw_cpu"
harness = false
