[package]
name = "clovers-cli"
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "clovers"
path = "src/main.rs"

[dependencies]
# Internal
clovers = { path = "../clovers" }
# External
rayon = "1.5.0"
rand = { version = "0.8.4", features = ["small_rng"], default-features = false }
serde = { version = "1.0.127", features = ["derive"], default-features = false }
serde_json = "1.0.60"
image = { version = "0.23.12" }
chrono = { version = "0.4.19" }
humantime = { version = "2.0.1" }
indicatif = { version = "0.16.0", features = ["rayon"] }
clap = { version = "3.0.0-beta.2" }
spirv-builder = { git = "https://github.com/EmbarkStudios/rust-gpu" }
wgpu = "0.9.0"
bytemuck = {version = "1.7.2", features = ["derive"]}
futures = "0.3.16"
env_logger = "0.9.0"
log = "0.4.14"
