[package]
name = "clovers-cli"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "clovers-cli"
path = "src/main.rs"

[dependencies]
# Internal
clovers = { path = "../clovers", features = ["serde-derive", "stl", "traces", "gl_tf"], default-features = false }

# External
clap = { version = "4.0.8", features = ["std", "derive"], default-features = false  }
human_format = "1.0.3"
humantime = "2.1.0"
image = { version =  "0.24.4", features = ["png"], default-features = false }
img-parts = "0.3.0"
indicatif = { version = "0.17.1", features = ["rayon"], default-features = false }
rand = { version = "0.8.5", features = ["small_rng", "getrandom"], default-features = false }
rayon = "1.5.3"
serde = { version = "1.0.145", features = ["derive"], default-features = false }
serde_json = { version = "1.0", features = ["alloc"], default-features = false }
time = { version = "0.3.14", default-features = false }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["time"] }
