[package]
name = "clovers-cli"
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "clovers"
path = "src/main.rs"

[dependencies]
# Internal
clovers = { path = "../clovers" }
# External
nalgebra = { version = "0.23.1", features = ["serde-serialize"] }
rayon = "1.5.0"
rand = "0.7.3"
serde = { version = "1.0.118", features = ["derive", "rc"] }
serde_json = "1.0.60"
image = { version = "0.23.12" }
chrono = { version = "0.4.19" }
humantime = { version = "2.0.1" }
indicatif = { version = "0.15.0", features = ["rayon"] }
clap = { version = "3.0.0-beta.2" }
toml = { version = "0.5.7" }
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", features = ["glam"] }
spirv-builder = { git = "https://github.com/EmbarkStudios/rust-gpu" }
syn = "1.0.75"
wgpu = "0.9.0"
bytemuck = {version = "1.7.2", features = ["derive"]}
futures = "0.3.16"
env_logger = "0.9.0"
log = "0.4.14"
