[package]
name = "clovers-cli"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "clovers-cli"
path = "src/main.rs"

[dependencies]
# Internal
clovers = { path = "../clovers", features = ["serde-derive", "stl", "traces", "gl_tf"], default-features = false }

# External
clap = { version = "4.0.29", features = ["std", "derive"], default-features = false  }
human_format = "1.0.3"
humantime = "2.1.0"
image = { version =  "0.24.5", features = ["png"], default-features = false }
img-parts = "0.3.0"
indicatif = { git = "https://github.com/console-rs/indicatif", rev = "2954b1a24ac5f1900a7861992e4825bff643c9e2", features = ["rayon"], default-features = false }
rand = { version = "0.8.5", features = ["small_rng", "getrandom"], default-features = false }
rayon = "1.6.1"
serde = { version = "1.0.150", features = ["derive"], default-features = false }
serde_json = { version = "1.0", features = ["alloc"], default-features = false }
time = { version = "0.3.17", default-features = false }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["time"] }
