[package]
name = "clovers-cli"
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "clovers"
path = "src/main.rs"

[dependencies]
# Internal
clovers = { path = "../clovers", features = ["serde-derive", "stl", "traces", "nalg", "rand-crate"]}
# External
rayon = "1.5.1"
rand = { version = "0.8.4", features = ["small_rng"], default-features = true }
serde = { version = "1.0.130", features = ["derive"], default-features = false }
serde_json = "1.0.67"
image = "0.23.14"
chrono = "0.4.19"
humantime = "2.1.0"
indicatif = { version = "0.16.2", features = ["rayon"] }
clap = "3.0.0-beta.4"
spirv-builder = { git = "https://github.com/EmbarkStudios/rust-gpu", rev = "eeb67ae7489e5df03231f73d108a8f2feae2ca1a" }
bytemuck = { version = "1.7.2", features = ["derive"] }
futures = "0.3.17"
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
# TODO: use a normal version after release of 0.11.0 or so, when web-sys dependency issue has been fixed and released
wgpu = { git = "https://github.com/gfx-rs/wgpu", features = ["spirv"], rev = "d50e74747d515f7e377f249a2918d3e62a33a57a" }
