[package]
name = "clovers-cli"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "clovers-cli"
path = "src/main.rs"

[dependencies]
# Internal
clovers = { path = "../clovers", features = ["serde-derive", "stl", "traces"]}
# External
rayon = "1.5.1"
rand = { version = "0.8.4", features = ["small_rng"], default-features = false }
serde = { version = "1.0.130", features = ["derive"], default-features = false }
serde_json = "1.0.67"
image = "0.23.14"
chrono = "0.4.19"
humantime = "2.1.0"
indicatif = { version = "0.16.2", features = ["rayon"] }
clap = { version = "3.1.8", features = ["derive"] }
spirv-builder = { git = "https://github.com/EmbarkStudios/rust-gpu", rev = "116bf9c4d413df7413ae931ee31b2777c7abf64e" }
bytemuck = { version = "1.7.2", features = ["derive"] }
futures = "0.3.17"
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
wgpu = { version = "0.12.0", features = ["spirv"] }
