name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
  lint: # inspired by https://github.com/EmbarkStudios/rust-gpu/blob/main/.github/workflows/ci.yaml
    runs-on: ubuntu-latest
    steps:
      - name: Install rustup components
        run: rustup component add rustfmt clippy
      - name: Install rust-toolchain # cargo version is a random command that forces the installation of rust-toolchain
        run: cargo version
      - name: cargo fetch --locked
        run: cargo fetch --locked
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Check docs are valid
        run: RUSTDOCFLAGS=-Dwarnings cargo doc --no-deps
      - name: Clippy
        run: cargo clippy
